const DEFAULT={settings:{name:"NUR Umrah & Hajj Travel",phone:"+880 1XXX-XXXXXX",whatsapp:"+880 1XXX-XXXXXX",email:"info@nurtravel.com",facebook:"https://www.facebook.com/share/1Ea8p2J5f5/",address:"Dhaka, Bangladesh",about:"NUR Umrah & Hajj Travel is dedicated to helping pilgrims plan their sacred journey with confidence and care.",accent:"#d8b25f",heroEyebrow:"A peaceful journey begins with the right guidance",heroTitle:"From your first step to the Holy Kaaba, we're with you.",heroText:"Professional Hajj and Umrah packages designed around your budget, travel dates and comfort.",heroButton:"Explore Packages"},packages:[{name:"Economy Hajj",type:"Hajj",days:"30–45 Days",price:"৳ 5,50,000",tag:"VALUE",hotel:"Comfort Hotel",desc:"Essential Hajj services and guidance."},{name:"Standard Umrah",type:"Umrah",days:"13–14 Days",price:"৳ 2,05,000",tag:"POPULAR",hotel:"4★ Hotel",desc:"Comfortable hotel, visa support and guidance."}],gallery:[{title:"Masjid al-Haram",url:"https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=1200&q=80"},{title:"Masjid an-Nabawi",url:"https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1200&q=80"}],reviews:[{name:"Pilgrim Review",text:"Alhamdulillah, the journey was smooth and the support was very helpful."}]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function clone(x){return JSON.parse(JSON.stringify(x))}
function getData(){try{const x=JSON.parse(localStorage.getItem("nurTravelData")||"null");if(!x)return clone(DEFAULT);return {...clone(DEFAULT),...x,settings:{...DEFAULT.settings,...(x.settings||{})},packages:Array.isArray(x.packages)?x.packages:clone(DEFAULT.packages),gallery:Array.isArray(x.gallery)?x.gallery:clone(DEFAULT.gallery),reviews:Array.isArray(x.reviews)?x.reviews:clone(DEFAULT.reviews)}}catch(e){return clone(DEFAULT)}}
function saveData(d){try{localStorage.setItem("nurTravelData",JSON.stringify(d));return true}catch(e){alert("Data save হচ্ছে না। ছবির size ছোট করে আবার চেষ্টা করুন।");return false}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function toast(t,m){const el=$("#toast");el.innerHTML=`<b>${esc(t)}</b><span>${esc(m)}</span>`;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2500)}
function bookings(){try{return JSON.parse(localStorage.getItem("nurBookings")||"[]")}catch(e){return[]}}
const SEEN="nurSeenBookingIds";function unseen(){let seen=[];try{seen=JSON.parse(localStorage.getItem(SEEN)||"[]")}catch(e){}return bookings().filter(x=>!seen.includes(x.id))}
function badges(){const n=unseen().length;["#notifBadge","#sideBadge"].forEach(id=>{const x=$(id);x.textContent=n>99?"99+":n;x.classList.toggle("show",n>0)})}
function go(tab){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===tab));const b=$(`.tab[data-tab="${tab}"]`);$("#pageTitle").textContent=b?.querySelector('label')?.textContent||tab;$("#pageHint").textContent={dashboard:"সবকিছু এক জায়গা থেকে সহজে পরিচালনা করুন।",quick:"Code ছাড়াই Website-এর তথ্য বদলান।",packages:"Hajj ও Umrah package manage করুন।",gallery:"Website-এর ছবি manage করুন।",reviews:"Customer feedback manage করুন।",bookings:"Customer booking enquiry দেখুন।"}[tab]||"";if(tab==='bookings'){localStorage.setItem(SEEN,JSON.stringify(bookings().map(x=>x.id)));badges()}}
function openModal(title,body){$("#modalTitle").textContent=title;$("#modalBody").innerHTML=body;$("#modal").classList.remove('hidden')}
function closeModal(){$("#modal").classList.add('hidden');$("#modalBody").innerHTML=''}
function render(){const d=getData();$("#statPackages").textContent=d.packages.length;$("#statGallery").textContent=d.gallery.length;$("#statReviews").textContent=d.reviews.length;$("#statBookings").textContent=bookings().length;fillQuick(d);renderPackages(d);renderGallery(d);renderReviews(d);renderBookings();badges()}
function fillQuick(d){const f=$("#quickForm");Object.entries(d.settings).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v})}
function renderPackages(d){const q=($("#packageSearch")?.value||'').toLowerCase();const filter=$(".filter.active")?.dataset.filter||'all';const arr=d.packages.map((p,i)=>({...p,_i:i})).filter(p=>(filter==='all'||p.type===filter)&&(`${p.name} ${p.type} ${p.hotel}`.toLowerCase().includes(q)));$("#packageAdmin").innerHTML=arr.length?arr.map(p=>`<article class="item-card"><div class="item-top"><div><span class="pill">${esc(p.type)}</span><h4>${esc(p.name)}</h4><p>${esc(p.days)} · ${esc(p.hotel)}</p></div><strong>${esc(p.price)}</strong></div><p>${esc(p.desc)}</p><div class="mini-actions"><button data-edit-package="${p._i}">✏️ Edit</button><button data-copy-package="${p._i}">📋 Copy</button><button class="delete" data-delete-package="${p._i}">🗑️ Delete</button></div></article>`).join(''):'<div class="empty">কোনো Package পাওয়া যায়নি।</div>'}
function renderGallery(d){$("#galleryAdmin").innerHTML=d.gallery.length?d.gallery.map((g,i)=>`<article class="item-card gallery-card"><img src="${esc(g.url)}" onerror="this.src='data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'800\' height=\'450\'%3E%3Crect width=\'100%\' height=\'100%\' fill=\'%23eef2ef\'/%3E%3Ctext x=\'50%\' y=\'50%\' dominant-baseline=\'middle\' text-anchor=\'middle\' font-size=\'28\' fill=\'%23727d77\'%3ENo image%3C/text%3E%3C/svg%3E'"><div class="item-top"><div><h4>${esc(g.title)}</h4><p>ছবি ${i+1}</p></div></div><div class="mini-actions"><button data-edit-gallery="${i}">✏️ Edit</button><button class="delete" data-delete-gallery="${i}">🗑️ Delete</button></div></article>`).join(''):'<div class="empty">Gallery খালি। “＋ ছবি যোগ করুন” চাপুন।</div>'}
function renderReviews(d){$("#reviewAdmin").innerHTML=d.reviews.length?d.reviews.map((r,i)=>`<article class="item-card"><div class="stars">★★★★★</div><h4>${esc(r.name)}</h4><p>“${esc(r.text)}”</p><div class="mini-actions"><button data-edit-review="${i}">✏️ Edit</button><button class="delete" data-delete-review="${i}">🗑️ Delete</button></div></article>`).join(''):'<div class="empty">Review নেই। “＋ Review যোগ করুন” চাপুন।</div>'}
function renderBookings(){const bs=bookings().slice().reverse();$("#bookingAdmin").innerHTML=bs.length?bs.map(b=>`<article class="booking"><div><b>${esc(b.name||'Unknown')}</b><span>${esc(b.phone||'')}</span></div><strong>${esc(b.package||'Package enquiry')}</strong><p>${b.date?`📅 ${esc(b.date)} · `:''}${esc(b.message||'No message')}</p><small>${esc(b.created||'')}</small></article>`).join(''):'<div class="empty">এখনও কোনো booking নেই।</div>'}
function packageForm(p={},i=null){openModal(i===null?'＋ নতুন Package':'✏️ Package Edit',`<form id="packageForm" class="modal-form"><label>Package Name<input name="name" value="${esc(p.name)}" required></label><div class="grid2"><label>Type<select name="type"><option ${p.type==='Umrah'?'selected':''}>Umrah</option><option ${p.type==='Hajj'?'selected':''}>Hajj</option></select></label><label>Days<input name="days" value="${esc(p.days)}"></label><label>Price<input name="price" value="${esc(p.price)}"></label><label>Hotel<input name="hotel" value="${esc(p.hotel)}"></label><label>Tag<input name="tag" value="${esc(p.tag)}"></label></div><label>Description<textarea name="desc" rows="4">${esc(p.desc)}</textarea><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary-btn">💾 Save Package</button></div></form>`);$("#packageForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=getData(),obj={name:f.get('name').trim(),type:f.get('type'),days:f.get('days').trim(),price:f.get('price').trim(),tag:f.get('tag').trim(),hotel:f.get('hotel').trim(),desc:f.get('desc').trim()};if(i===null)d.packages.push(obj);else d.packages[i]=obj;if(saveData(d)){closeModal();render();toast('Saved','Package সফলভাবে Save হয়েছে।')}}}
function galleryForm(g={},i=null){openModal(i===null?'📷 নতুন ছবি':'📷 Gallery Edit',`<form id="galleryForm" class="modal-form"><div class="upload-box"><img id="modalPreview" src="${esc(g.url||'')}" onerror="this.style.display='none'"><label class="upload-btn">📱 Phone Gallery থেকে ছবি নিন<input id="galleryFile" type="file" accept="image/*"></label><small>ছোট/মাঝারি ছবি ব্যবহার করলে demo storage ভালো কাজ করবে।</small></div><label>Image Title<input name="title" value="${esc(g.title||'New Photo')}" required></label><label>Image URL <span class="muted">(ঐচ্ছিক)</span><input id="imageUrl" name="url" value="${esc(g.url||'')}" placeholder="https://..."></label><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary-btn">💾 Save Image</button></div></form>`);const file=$("#galleryFile"),prev=$("#modalPreview"),url=$("#imageUrl");file.onchange=()=>{const f=file.files?.[0];if(!f)return;if(f.size>2.5*1024*1024){alert('Demo-তে 2.5 MB-এর নিচের ছবি নিন।');file.value='';return}const rd=new FileReader();rd.onload=()=>{url.value=rd.result;prev.src=rd.result;prev.style.display='block'};rd.readAsDataURL(f)};url.oninput=()=>{if(url.value){prev.src=url.value;prev.style.display='block'}};$("#galleryForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=getData(),obj={title:f.get('title').trim(),url:f.get('url').trim()};if(!obj.url){alert('একটি ছবি নির্বাচন করুন বা Image URL দিন।');return}if(i===null)d.gallery.push(obj);else d.gallery[i]=obj;if(saveData(d)){closeModal();render();toast('Saved','ছবি Save হয়েছে।')}}}
function reviewForm(r={},i=null){openModal(i===null?'⭐ নতুন Review':'⭐ Review Edit',`<form id="reviewForm" class="modal-form"><label>Customer Name<input name="name" value="${esc(r.name||'')}" required></label><label>Review<textarea name="text" rows="5" required>${esc(r.text||'')}</textarea></label><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary-btn">💾 Save Review</button></div></form>`);$("#reviewForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=getData(),obj={name:f.get('name').trim(),text:f.get('text').trim()};if(i===null)d.reviews.push(obj);else d.reviews[i]=obj;if(saveData(d)){closeModal();render();toast('Saved','Review Save হয়েছে।')}}}
function confirmDelete(kind,i){if(!confirm('আপনি কি সত্যিই এটি Delete করতে চান?'))return;const d=getData();d[kind].splice(i,1);if(saveData(d)){render();toast('Deleted','Delete হয়েছে।')}}
function init(){
$("#loginBtn").onclick=()=>{if($("#pass").value==='admin1234'){sessionStorage.setItem('nurAdmin','1');$("#login").classList.add('hidden');$("#app").classList.remove('hidden');render()}else alert('Password ভুল হয়েছে।')};
if(sessionStorage.getItem('nurAdmin')==='1'){$("#login").classList.add('hidden');$("#app").classList.remove('hidden');render()}
$$('.tab').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$("#quickForm").onsubmit=e=>{e.preventDefault();const f=e.target,d=getData();Object.keys(d.settings).forEach(k=>{if(f.elements[k])d.settings[k]=f.elements[k].value});if(saveData(d)){render();toast('Saved','Website settings Save হয়েছে।')}};$("#quickForm").addEventListener('change',()=>{});$("[data-save-quick]").onclick=()=>$("#quickForm").requestSubmit();
$$('[data-color]').forEach(b=>b.onclick=()=>$("#quickForm").elements.accent.value=b.dataset.color);
$("#addPackage").onclick=()=>packageForm();$("#addGallery").onclick=()=>galleryForm();$("#addReview").onclick=()=>reviewForm();
$("#packageSearch").oninput=()=>renderPackages(getData());$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPackages(getData())});
$("#packageAdmin").onclick=e=>{const b=e.target.closest('button');if(!b)return;const d=getData();if(b.dataset.editPackage!==undefined)packageForm(d.packages[+b.dataset.editPackage],+b.dataset.editPackage);if(b.dataset.copyPackage!==undefined){d.packages.push({...d.packages[+b.dataset.copyPackage],name:d.packages[+b.dataset.copyPackage].name+' Copy'});if(saveData(d))render()};if(b.dataset.deletePackage!==undefined)confirmDelete('packages',+b.dataset.deletePackage)};
$("#galleryAdmin").onclick=e=>{const b=e.target.closest('button');if(!b)return;const d=getData();if(b.dataset.editGallery!==undefined)galleryForm(d.gallery[+b.dataset.editGallery],+b.dataset.editGallery);if(b.dataset.deleteGallery!==undefined)confirmDelete('gallery',+b.dataset.deleteGallery)};
$("#reviewAdmin").onclick=e=>{const b=e.target.closest('button');if(!b)return;const d=getData();if(b.dataset.editReview!==undefined)reviewForm(d.reviews[+b.dataset.editReview],+b.dataset.editReview);if(b.dataset.deleteReview!==undefined)confirmDelete('reviews',+b.dataset.deleteReview)};
$("#bookingAdmin").onclick=e=>{};$("#clearBookings").onclick=()=>{if(confirm('সব booking Delete করবেন?')){localStorage.removeItem('nurBookings');localStorage.removeItem(SEEN);render()}};
$("#reset").onclick=()=>{if(confirm('সব demo data reset করবেন?')){localStorage.removeItem('nurTravelData');localStorage.removeItem('nurBookings');localStorage.removeItem(SEEN);render();toast('Reset','Demo data reset হয়েছে।')}};
$("#closeModal").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==='modal'||e.target.matches('[data-close]'))closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$("#notifyBtn").onclick=async()=>{if(!('Notification' in window)){toast('Not supported','এই browser notification support করে না।');return}const p=await Notification.requestPermission();toast(p==='granted'?'Enabled':'Blocked',p==='granted'?'Notification চালু হয়েছে।':'Chrome settings থেকে Allow করুন।')};
let last=bookings().length;setInterval(()=>{const n=bookings().length;if(n>last){toast('🔔 New Booking', 'নতুন customer booking এসেছে।');badges();try{if(Notification.permission==='granted')new Notification('NUR Travel — New Booking')}catch(e){}}last=n},2000);
}
init();
