const defaultData={settings:{name:"NUR Umrah & Hajj Travel",phone:"+880 1XXX-XXXXXX",whatsapp:"+880 1XXX-XXXXXX",email:"info@nurtravel.com",address:"Your office address, Dhaka, Bangladesh",about:"NUR Umrah & Hajj Travel is dedicated to helping pilgrims plan their sacred journey with confidence. We focus on clear package information, practical travel coordination and responsive assistance.",accent:"#d9b25f"},packages:[{name:"Economy Umrah",type:"Umrah",days:"10 Days",price:"৳ 95,000",tag:"BEST VALUE",hotel:"3★ Hotel",desc:"A practical package for budget-conscious pilgrims."},{name:"Standard Umrah",type:"Umrah",days:"14 Days",price:"৳ 125,000",tag:"POPULAR",hotel:"4★ Hotel",desc:"Comfortable accommodation with balanced services."},{name:"Premium Umrah",type:"Umrah",days:"21 Days",price:"৳ 185,000",tag:"PREMIUM",hotel:"5★ Hotel",desc:"Enhanced comfort and dedicated support."},{name:"Economy Hajj",type:"Hajj",days:"30–45 Days",price:"৳ 5,50,000",tag:"ECONOMY",hotel:"AC Hotel",desc:"Value-focused Hajj package with essential services."}],gallery:[{title:"Masjid al-Haram",url:"https://images.unsplash.com/photo-1564769625392-651b89c31e2a?auto=format&fit=crop&w=1200&q=85"}],reviews:[{name:"Pilgrim Review",text:"Alhamdulillah, the journey was smooth and the support was very helpful."}]};
function data(){return JSON.parse(localStorage.getItem("nurTravelData")||JSON.stringify(defaultData))}
function save(d){localStorage.setItem("nurTravelData",JSON.stringify(d))}
const $=s=>document.querySelector(s);
if(sessionStorage.getItem("nurAdmin")==="1") openApp();
$("#loginBtn").onclick=()=>{if($("#pass").value==="admin1234"){sessionStorage.setItem("nurAdmin","1");openApp()}else alert("Wrong password")};
function openApp(){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");renderAll()}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.tab).classList.add("active");$("#pageTitle").textContent=b.textContent.replace(/^[^A-Za-z]+/,"")});
$("#reset").onclick=()=>{if(confirm("Reset all demo data?")){localStorage.removeItem("nurTravelData");localStorage.removeItem("nurBookings");renderAll()}};
function renderAll(){const d=data();$("#statPackages").textContent=d.packages.length;$("#statGallery").textContent=d.gallery.length;$("#statReviews").textContent=d.reviews.length;$("#statBookings").textContent=JSON.parse(localStorage.getItem("nurBookings")||"[]").length;renderSettings(d);renderPackages(d);renderGallery(d);renderReviews(d);renderBookings()}
function renderSettings(d){const f=$("#settingsForm");Object.keys(d.settings).forEach(k=>{if(f[k])f[k].value=d.settings[k]});f.onsubmit=e=>{e.preventDefault();const x=data();for(const k of Object.keys(x.settings))if(f[k])x.settings[k]=f[k].value;save(x);alert("Settings saved");renderAll()}}
function renderPackages(d){$("#packageAdmin").innerHTML=d.packages.map((p,i)=>`<div class="admin-row"><div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input data-k="name" value="${esc(p.name)}"><select data-k="type"><option ${p.type==="Umrah"?"selected":""}>Umrah</option><option ${p.type==="Hajj"?"selected":""}>Hajj</option></select><input data-k="days" value="${esc(p.days)}"><input data-k="price" value="${esc(p.price)}"><input data-k="tag" value="${esc(p.tag)}"><input data-k="hotel" value="${esc(p.hotel)}"></div><textarea data-k="desc" rows="2">${esc(p.desc)}</textarea></div><div class="actions"><button class="save" onclick="savePackage(${i},this)">Save</button><button class="del" onclick="delPackage(${i})">Delete</button></div></div>`).join("")}
window.savePackage=(i,btn)=>{const row=btn.closest(".admin-row"),d=data();row.querySelectorAll("[data-k]").forEach(x=>d.packages[i][x.dataset.k]=x.value);save(d);alert("Package saved");renderAll()};
window.delPackage=i=>{const d=data();d.packages.splice(i,1);save(d);renderAll()};
$("#addPackage").onclick=()=>{const d=data();d.packages.push({name:"New Package",type:"Umrah",days:"14 Days",price:"৳ 0",tag:"NEW",hotel:"Hotel",desc:"Add package details here."});save(d);renderAll()};
function renderGallery(d){$("#galleryAdmin").innerHTML=d.gallery.map((g,i)=>`<div class="admin-row"><div><input data-g="title" value="${esc(g.title)}"><input data-g="url" value="${esc(g.url)}"></div><div class="actions"><button class="save" onclick="saveGallery(${i},this)">Save</button><button class="del" onclick="delGallery(${i})">Delete</button></div></div>`).join("")}
window.saveGallery=(i,b)=>{const d=data(),r=b.closest(".admin-row");r.querySelectorAll("[data-g]").forEach(x=>d.gallery[i][x.dataset.g]=x.value);save(d);renderAll()};
window.delGallery=i=>{const d=data();d.gallery.splice(i,1);save(d);renderAll()};
$("#addGallery").onclick=()=>{const d=data();d.gallery.push({title:"New Photo",url:"https://images.unsplash.com/photo-1564769625392-651b89c31e2a?auto=format&fit=crop&w=900&q=80"});save(d);renderAll()};
function renderReviews(d){$("#reviewAdmin").innerHTML=d.reviews.map((r,i)=>`<div class="admin-row"><div><input data-r="name" value="${esc(r.name)}"><textarea data-r="text" rows="2">${esc(r.text)}</textarea></div><div class="actions"><button class="save" onclick="saveReview(${i},this)">Save</button><button class="del" onclick="delReview(${i})">Delete</button></div></div>`).join("")}
window.saveReview=(i,b)=>{const d=data(),r=b.closest(".admin-row");r.querySelectorAll("[data-r]").forEach(x=>d.reviews[i][x.dataset.r]=x.value);save(d);renderAll()};
window.delReview=i=>{const d=data();d.reviews.splice(i,1);save(d);renderAll()};
$("#addReview").onclick=()=>{const d=data();d.reviews.push({name:"New Pilgrim",text:"Write review here."});save(d);renderAll()};
function renderBookings(){const bs=JSON.parse(localStorage.getItem("nurBookings")||"[]");$("#bookingAdmin").innerHTML=bs.length?bs.map(b=>`<div class="booking-card"><b>${esc(b.name)}</b> — ${esc(b.phone)}<div>${esc(b.package)} ${b.date?"• "+esc(b.date):""}</div><p>${esc(b.message||"No message")}</p><span class="muted">${esc(b.created)}</span></div>`).join(""):"<p class='muted'>No booking enquiries yet.</p>"}
$("#clearBookings").onclick=()=>{if(confirm("Clear all bookings?")){localStorage.removeItem("nurBookings");renderAll()}};
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
